spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/db_example
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  properties:
    # Hibernate 설정 (optional)
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
